recipe_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings #allows access to MEDIA_URL and MEDIA_ROOT
from django.conf.urls.static import static # helper function; create URLs from local folder names
from django.views.generic import TemplateView
from .views import login_view, logout_view

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("recipes.urls")),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path(
        "success/",
        TemplateView.as_view(template_name="recipes/success.html"),
        name="success",
    ),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path, include
from .views import recipes_home, export_recipes_csv, about_page, generate_chart, add_recipe
from .views import RecipesListView, RecipesDetailView
from django.conf.urls.static import static
from django.conf import settings

app_name = "recipes"

urlpatterns = [
    path("", recipes_home, name="recipes_home"),
    path("recipes/add/", add_recipe, name="add_recipe"),
    path("recipes/export/", export_recipes_csv, name="export_csv"),
    path("generate-chart/", generate_chart, name="generate_chart"),
    path("recipes/", RecipesListView.as_view(), name="recipes_list"),
    path("list/<pk>", RecipesDetailView.as_view(), name="detail"),
    path("about/", about_page, name="about"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/models.py
from django.db import models
from django.shortcuts import reverse

class Recipe(models.Model):
    name = models.CharField(max_length=100)
    cooking_time = models.PositiveIntegerField()
    description = models.TextField(default="this recipe doesn't have a description yet")
    difficulty = models.CharField(max_length=20, default="N/A")
    ingredients = models.ManyToManyField('ingredients.Ingredient', through='recipesingredients.RecipeIngredient', related_name='recipes')
    pic = models.ImageField(upload_to='recipes', default='no_picture.png') # default stored in src/media

    def calc_difficulty(self):
        num_ingredients = self.ingredients.count()

        if self.cooking_time < 10:
            if num_ingredients < 4:
                return "Easy"
            else:
                return "Medium"
        else:
            if num_ingredients < 4:
                return "Intermediate"
            else:
                return "Hard"
            
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.difficulty = self.calc_difficulty()
        super().save(update_fields=["difficulty"])

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse ("recipes:detail", kwargs={'pk': self.pk})

recipes/forms.py
from django import forms
from recipes.models import Recipe
from ingredients.models import Ingredient

CHART_CHOICES = (
    ("#1", "Bar Chart"),
    ("#2", "Pie Chart"),
    ("#3", "Line Chart"),
)

class RecipeSearchForm(forms.Form):
    Recipe_Name = forms.CharField(
        required=False,
        max_length=100,
        label="Recipe Name",
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Enter a Recipe Name"}
        ),
    )

    Ingredients = forms.ModelMultipleChoiceField(
        required=False,
        queryset=Ingredient.objects.order_by('name'),
        label="Ingredients",
        widget=forms.SelectMultiple(attrs={"class": "form-control"}),
    )

    chart_type = forms.ChoiceField(
        choices=CHART_CHOICES,
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
        label="Chart Type",
    )

    def clean(self):
        cleaned_data = super().clean()
        recipe_name = cleaned_data.get("Recipe_Name")
        ingredients = cleaned_data.get("Ingredients")

        if not recipe_name and not ingredients:
            raise forms.ValidationError("Please enter a recipe name or select ingredients.")
        return cleaned_data


class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        exclude = ["difficulty"]  # Exclude the 'difficulty' field from the form
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-item"}),
            "cooking_time": forms.NumberInput(attrs={"class": "form-item"}),
            "description": forms.Textarea(attrs={"class": "form-item"}),
            "ingredients": forms.SelectMultiple(
                attrs={
                    "class": "form-item",
                    "name": "Please select an item from the list. Hold CTRL to select multiple items",
                }
            ),
            "pic": forms.FileInput(attrs={"class": "form-item"}),
        }


class NewIngredientForm(forms.Form):
    new_ingredient = forms.CharField(
        max_length=255,
        required=False,
        help_text="Add a new ingredient",
        widget=forms.TextInput(attrs={"class": "form-item"}),
    )

recipes/views.py
from io import BytesIO
import base64
import logging
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from typing import Any, Dict
from django.db.models import Q
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, JsonResponse, Http404
from django.core.paginator import Paginator
from django.forms import formset_factory
from django.db import transaction

from .models import Recipe
from recipesingredients.models import RecipeIngredient
from .forms import RecipeSearchForm, RecipeForm, NewIngredientForm
from ingredients.models import Ingredient


# Create your views here.
def recipes_home(request):
    return render(request, "recipes/recipes_home.html")

def get_chart(chart_type, data, **kwargs):
    plt.switch_backend("AGG")
    fig = plt.figure(figsize=(12, 8), dpi=100)
    ax = fig.add_subplot(111)

    if chart_type == "#1":
        # Bar Chart
        plt.title("Cooking Time by Recipe", fontsize=20)
        plt.bar(data["name"], data["cooking_time"])
        plt.xlabel("Recipes", fontsize=16)
        plt.ylabel("Cooking Time (min)", fontsize=16)
    elif chart_type == "#2":
        # Pie Chart
        plt.title("Recipes Cooking Time Comparison", fontsize=20)
        labels = kwargs.get("labels")
        plt.pie(data["cooking_time"], labels=None, autopct="%1.1f%%")
        plt.legend(
            data["name"],
            loc="upper right",
            bbox_to_anchor=(1.0, 1.0),
            fontsize=12,
        )
    elif chart_type == "#3":
        # Line Chart
        plt.title("Cooking Time by Recipe", fontsize=20)
        x_values = data["name"].to_numpy()  # Convert to numpy array
        y_values = data["cooking_time"].to_numpy()  # Convert to numpy array
        plt.plot(x_values, y_values)
        plt.xlabel("Recipes", fontsize=16)
        plt.ylabel("Cooking Time (min)", fontsize=16)
    else:
        print("Unknown chart type.")

    plt.tight_layout(pad=3.0)

    # Convert the plot to an image
    buffer = BytesIO()
    plt.savefig(buffer, format="png")
    buffer.seek(0)
    chart_image = base64.b64encode(buffer.read()).decode("utf-8")

    return chart_image

class RecipesListView(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = "recipes/recipes_list.html"
    context_object_name = "recipes"
    paginate_by = 12

    def get_queryset(self):
        queryset = super().get_queryset()
        recipe_name = self.request.GET.get("Recipe_Name")
        ingredients = self.request.GET.getlist("Ingredients")
        selected_ingredient = self.request.GET.get("selected_ingredient")

        if recipe_name:
            queryset = queryset.filter(name__icontains=recipe_name)

        if ingredients:
            ingredient_query = Q()
            for ingredient_id in ingredients:
                ingredient_query |= Q(ingredients__id=ingredient_id)
            queryset = queryset.filter(ingredient_query)

        # Include selected ingredient in the filter
        if selected_ingredient:
            queryset = queryset.filter(ingredients__id=selected_ingredient)

        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        try:
            # Convert the QuerySet to a pandas DataFrame
            df = pd.DataFrame.from_records(context["recipes"].values())
            context["recipes_df"] = df

            context["form"] = RecipeSearchForm(self.request.GET)

            # Generate and pass the chart paths to the context
            chart_type = self.request.GET.get("chart_type")
            if chart_type:
                chart_data = {"name": df["name"], "cooking_time": df["cooking_time"]}
                if chart_type == "#1":
                    chart_data["labels"] = df["name"]
                elif chart_type == "#2":
                    chart_data["labels"] = df["name"]
                else:
                    chart_data["labels"] = None

                chart_image = get_chart(chart_type, chart_data)
                context["chart_image"] = chart_image

        except KeyError:
            # If KeyError occurs, handle the error and set the appropriate context variables
            context["recipes"] = []  # Set an empty list to recipes
            context[
                "error_message"
            ] = "There are no recipes with that combination of ingredients."

        return context


@login_required
def export_recipes_csv(request):
    # Get the filter parameters from the request
    recipe_name = request.GET.get("Recipe_Name")
    ingredients = request.GET.getlist("Ingredients")

    # Filter the Recipe objects based on the request parameters
    queryset = Recipe.objects.all()

    if recipe_name:
        queryset = queryset.filter(name__icontains=recipe_name)

    if ingredients:
        for ingredient in ingredients:
            # Check if the ingredient parameter is empty
            if ingredient:
                queryset = queryset.filter(ingredients__id=ingredient)

    # Convert the filtered QuerySet to a list of dictionaries
    recipe_data = list(queryset.values())

    # Get the related Ingredient data for each recipe
    for data in recipe_data:
        recipe = Recipe.objects.get(pk=data["id"])
        data["ingredients"] = ", ".join(
            [ingredient.name for ingredient in recipe.ingredients.all()]
        )

    # Create the DataFrame from the list of dictionaries
    df = pd.DataFrame.from_records(recipe_data)

    response = HttpResponse(content_type="text/csv")
    response["Content-Disposition"] = 'attachment; filename="recipes.csv"'
    df.to_csv(path_or_buf=response, index=False)
    return response


@login_required
def generate_chart(request):
    chart_type = request.GET.get("chart_type")
    recipe_name = request.GET.get("Recipe_Name")
    ingredients = request.GET.getlist("Ingredients")

    # Filter the Recipe objects based on the request parameters
    queryset = Recipe.objects.all()

    if recipe_name:
        queryset = queryset.filter(name__icontains=recipe_name)

    if ingredients:
        for ingredient in ingredients:
            # Check if the ingredient parameter is empty
            if ingredient:
                queryset = queryset.filter(ingredients__id=ingredient)

    # Convert the filtered QuerySet to a list of dictionaries
    recipe_data = list(queryset.values())

    # Get the related Ingredient data for each recipe
    for data in recipe_data:
        recipe = Recipe.objects.get(pk=data["id"])
        data["ingredients"] = ", ".join(
            [ingredient.name for ingredient in recipe.ingredients.all()]
        )

    # Create the DataFrame from the list of dictionaries
    df = pd.DataFrame.from_records(recipe_data)

    chart_data = {"name": df["name"], "cooking_time": df["cooking_time"]}
    if chart_type == "#1":
        chart_data["labels"] = df["name"]
    elif chart_type == "#2":
        # For Pie Chart, labels should be the recipe names, and not the cooking times
        chart_data["labels"] = df["name"]
    else:
        chart_data["labels"] = None

    chart_image = get_chart(chart_type, chart_data)
    return JsonResponse({"chart_image": chart_image})


@login_required
def about_page(request):
    return render(request, "recipes/about.html")


class RecipesDetailView(LoginRequiredMixin, DetailView):
    model = Recipe
    template_name = "recipes/details.html"
    context_object_name = "recipe"


logger = logging.getLogger(__name__)

@login_required
def add_recipe(request):
    IngredientFormSet = formset_factory(NewIngredientForm, extra=1, max_num=5)

    if request.method == "POST":
        form = RecipeForm(request.POST, request.FILES)
        formset = IngredientFormSet(request.POST)

        if form.is_valid() and formset.is_valid():
            try:
                recipe = form.save(commit=False)

                selected_ingredients_count = len(form.cleaned_data["ingredients"])
                new_ingredients_count = sum(
                    1
                    for ingredient_form in formset
                    if ingredient_form.cleaned_data.get("new_ingredient")
                )
                total_ingredients = selected_ingredients_count + new_ingredients_count

                if recipe.cooking_time < 10 and total_ingredients < 4:
                    recipe.difficulty = "Easy"
                elif recipe.cooking_time < 10 and total_ingredients >= 4:
                    recipe.difficulty = "Medium"
                elif recipe.cooking_time >= 10 and total_ingredients < 4:
                    recipe.difficulty = "Intermediate"
                else:
                    recipe.difficulty = "Hard"

                recipe.save()
                form.save_m2m()

                for ingredient_form in formset:
                    new_ingredient_name = ingredient_form.cleaned_data.get("new_ingredient")
                    print(f"New Ingredient Name: {new_ingredient_name}")
                    if new_ingredient_name:
                        ingredient, created = Ingredient.objects.get_or_create(name=new_ingredient_name)
                        RecipeIngredient.objects.create(recipe=recipe, ingredient=ingredient)

                messages.success(request, "Recipe added successfully.")

                if "save_and_add" in request.POST:
                    return redirect("recipes:add_recipe")

                return redirect(recipe)

            except Exception as e:
                # Log detailed error information
                logger.error("Error while saving recipe for user %s: %s", request.user.username, str(e))
                messages.error(request, "Error while saving recipe. Please try again.")

        else:
            # Log form and formset errors for debugging

recipes/templates/recipes/about.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
        integrity="sha384-KyZXEAg3QhqLMpG8r+Jf0Jt9OHo9z1rq9z6H+6n5p3DqP5F5KnsF5CEkVR+tg2F5F5" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Fuggles&family=Mooli&family=Roboto:wght@300&display=swap"
        rel="stylesheet">
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 200px;
            font-family: 'Roboto';
            text-align: left;
            letter-spacing: 0px;
            background-image: url("{% static 'recipes/images/background.png' %}");
            background-size: cover;
            background-attachment: fixed;
            background-position: center;
            color: rgb(188, 188, 188);
            text-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }

        .container {
            width: 40%;
            margin: 20px auto;
            padding: 50px;
            padding-top: 50px;
            background-color: rgba(0, 0, 0, 0.7);
            outline: 1px solid transparent;
            outline-color: rgba(255, 255, 255, .3);
            outline-offset: -15px;
            box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.5);
            position: absolute;
            top: 10px;
        }


        .card-title {
            font-size: 11vw;
            color: rgb(188, 188, 188);
            text-shadow: 8px 8px 8px rgba(0, 0, 0, 0.963);
            font-family: 'Fuggles', cursive;
            text-transform: capitalize;
            text-align: center;
            line-height: .8;
            margin-bottom: 28px;
        }

        .image-container {
            position: relative;
            width: 100%;
            height: 0;
            padding-top: 50%;
            overflow: hidden;
            border-radius: 12px;
            box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.5);
        }

        .image {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .back-button {
            position: fixed;
            font-family: 'Roboto';
            font-size: 15px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.963);
            box-shadow: 8px 8px 8px rgba(0, 0, 0, 0.5);
            font-weight: bold;
            letter-spacing: 2px;
            top: 8px;
            left: 10px;
            display: inline-block;
            padding: 10px 20px;
            background-color: rgba(56, 56, 56, 0.8);
            color: rgb(188, 188, 188);
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

        .back-button:hover {
            background-color: #555;
        }

        .logout-button {
            position: fixed;
            font-family: 'Roboto';
            font-size: 15px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.963);
            box-shadow: 8px 8px 8px rgba(0, 0, 0, 0.5);
            font-weight: bold;
            letter-spacing: 2px;
            top: 8px;
            right: 20px;
            display: inline-block;
            padding: 10px 20px;
            background-color: rgba(56, 56, 56, 0.8);
            color: rgb(188, 188, 188);
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

        .logout-button:hover {
            background-color: #555;
        }

        ::-webkit-scrollbar {
            width: 10px;
            /* Set the width of the scrollbar */
        }

        ::-webkit-scrollbar-track {
            background-color: rgba(0, 0, 0, 0.3);
            /* Track background color */
        }

        ::-webkit-scrollbar-thumb {
            background-color: rgb(112, 112, 112);
            /* Thumb color */
            border-radius: 10px;
            /* Rounded corners for the thumb */
        }
    </style>
</head>

<body class="scrollbar">
    <a href="{% url 'recipes:recipes_list' %}" class="back-button">Back</a>
    <a href="{% url 'logout' %}" class="logout-button">Logout</a>
    <div class="container mt-5">
        <div class="card">
            <div class="card-title">About Me</div>

            <div class="card-body">
                <div class="image-container">
                    <img src="{{ object.pic.url }}" class="image">
                </div>
                <p class="card-text">
                    Hi there! I'm Vadym. I just created this app and I am finishing it up now. <br>
                    Cheers!
                </p>
                <p class="card-text">I have experience in:</p>
                <ul>
                    <li>Python</li>
                    <li>JavaScript</li>
                    <li>HTML</li>
                    <li>CSS</li>
                </ul>
            </div>
        </div>
    </div>
    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-KyZXEAg3QhqLMpG8r+Jf0Jt9OHo9z1rq9z6H+6n5p3DqP5F5KnsF5CEkVR+tg2F5F5"
        crossorigin="anonymous"></script>
</body>

</html>

recipes/templates/recipes/add_recipe.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Recipe</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
        integrity="sha384-KyZXEAg3QhqLMpG8r+Jf0Jt9OHo9z1rq9z6H+6n5p3DqP5F5KnsF5CEkVR+tg2F5F5" crossorigin="anonymous">
    <link
        href="https://fonts.googleapis.com/css2?family=Dancing+Script&family=Fuggles&family=Mooli&family=Roboto:wght@300&display=swap"
        rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-KyZXEAg3QhqLMpG8r+Jf0Jt9OHo9z1rq9z6H+6n5p3DqP5F5KnsF5CEkVR+tg2F5F5"
        crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 200px;
            font-family: 'Roboto';
            text-align: left;
            letter-spacing: 0px;
            background-image: url("{% static 'recipes/images/background.png' %}");
            background-size: cover;
            background-attachment: fixed;
            background-position: center;
            color: rgb(188, 188, 188);
            text-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
        }

        .container {
            width: 40%;
            margin: 20px auto;
            padding: 50px;
            padding-top: 50px;
            background-color: rgba(0, 0, 0, 0.7);
            outline: 1px solid transparent;
            outline-color: rgba(255, 255, 255, .3);
            outline-offset: -15px;
            box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.5);
            position: absolute;
            top: 10px;
        }

        .card-title {
            font-size: 8vw;
            color: rgb(255, 255, 255);
            text-shadow: 8px 8px 8px rgba(0, 0, 0, 0.963);
            font-family: 'Fuggles', cursive;
            text-align: center;
            line-height: .8;
            margin-bottom: 28px;
        }


        .header {
            background-color: rgba(0, 0, 0, 0.7);
            padding: 20px;
        }

        .header a {
            text-decoration: none;
            color: #fff;
            font-weight: bold;
        }

        .recipe-form-container {
            width: 40%;
            margin-top: 100px;
            padding: 50px;
            padding-top: 50px;
            background-color: rgba(0, 0, 0, 0.7);
            outline: 1px solid transparent;
            outline-color: rgba(255, 255, 255, .3);
            outline-offset: -15px;
            box-shadow: 10px 10px 10px rgba(0, 0, 0, 0.5);
            position: absolute;
            top: 10px;
        }

        .form-item {
            margin-bottom: 20px;
        }

        label {
            font-weight: bold;
        }

        .back-button {
            position: fixed;
            font-family: 'Roboto';
            font-size: 20px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.963);
            box-shadow: 8px 8px 8px rgba(0, 0, 0, 0.5);
            font-weight: bold;
            letter-spacing: 2px;
            top: 10px;
            left: 20px;
            display: inline-block;
            padding: 10px 20px;
            color: rgb(188, 188, 188);
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

        .back-button:hover {
            background-color: #555;
        }

        .logout-button {
            position: fixed;
            font-family: 'Roboto';
            font-size: 10px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.963);
            box-shadow: 8px 8px 8px rgba(0, 0, 0, 0.5);
            font-weight: bold;
            letter-spacing: 2px;
            top: 10px;
            right: 20px;
            display: inline-block;
            padding: 10px 20px;
            color: rgb(188, 188, 188);
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

        .logout-button:hover {
            background-color: #555;
        }

        .about-button {
            position: fixed;
            font-family: 'Roboto';
            font-size: 10px;
            text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.963);
            box-shadow: 8px 8px 8px rgba(0, 0, 0, 0.5);
            font-weight: bold;
            letter-spacing: 2px;
            top: 10px;
            right: 130px;
            display: inline-block;
            padding: 10px 20px;
            color: rgb(188, 188, 188);
            text-decoration: none;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

        .about-button:hover {
            background-color: #555;
        }

        .top-bar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            background-color: rgba(0, 0, 0, 0.87);
            outline: 2px solid transparent;
            outline-color: rgba(255, 255, 255, .1);
            padding: 23px;
            position: fixed;
            top: 0;
            left: 0;
            right: 0;
            z-index: 999;
            box-shadow: 0px 2px 4px rgba(0, 0, 0, 0.2);
            width: 100%;
        }

        .top-bar a {
            text-decoration: none;
            color: #fff;
            font-size: 15px;
            font-weight: bold;
            padding-top: 5px;
            padding-bottom: 5px;
            padding-left: 10px;
            padding-right: 10px;
            border-radius: 5px;
            transition: background-color 0.3s, color 0.3s;
        }

        .top-bar a:hover {
            background-color: rgba(255, 255, 255, 0.2);
        }
    </style>
</head>

<body class="add-recipe">
    <div class="top-bar">
        <a href="{% url 'recipes:recipes_list' %}" class="back-button">Back</a>
        <a href="{% url 'recipes:add_recipe' %}" class="about-button">Add Recipe</a>
        <a href="{% url 'logout' %}" class="logout-button">Logout</a>
    </div>
    <div class="container recipe-form-container mt-5">
        <div class="card-title">Add a New Recipe</div>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form-group">
                <label for="{{ form.name.id_for_label }}">Name of Recipe:</label><br>
                {{ form.name }}
            </div>
            <div class="form-group">
                <label for="{{ form.cooking_time.id_for_label }}">Cooking Time (min):</label><br>
                {{ form.cooking_time }}
            </div>
            <div class="form-group">
                <label for="{{ form.description.id_for_label }}">Description:</label><br>
                {{ form.description }}
            </div>
            <div class="form-group">
                <label for="{{ form.ingredients.id_for_label }}">Ingredients:</label><br><br>
                {{ form.ingredients }}
            </div>
            <div id="new-ingredients-container">
                <h3 class="mb-3">New Ingredient(s):</h3>
                <div id="formset-container">
                    {{ formset.management_form }}
                    {% for form in formset %}
                    <div class="form-group">{{ form.new_ingredient }}</div>
                    {% endfor %}
                </div>
                <button type="button" id="add-another-btn" class="btn btn-secondary">Add Another Ingredient</button><br>
            </div> <!-- This closing tag was missing -->
            <div class="form-group">
                <label for="{{ form.pic.id_for_label }}"><br>Image:</label><br>
                {{ form.pic }}
            </div>
            <div class="button-container">
                <button type="submit" class="save-button btn btn-primary">Save Recipe</button>
                <button type="submit" class="save-add-another-button btn btn-success" name="save_and_add">Save & Add
                    Another Recipe</button>
            </div>
        </form>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const formsetContainer = document.getElementById("formset-container");
            const addAnotherBtn = document.getElementById("add-another-btn");
            const totalFormsInput = document.querySelector(
                'input[name="form-TOTAL_FORMS"]'
            );

            addAnotherBtn.addEventListener("click", function () {
                const originalForm = document.querySelector(
                    "#formset-container .form-group"
                );
                const clonedForm = originalForm.cloneNode(true);
                const newIngredientInput = clonedForm.querySelector('input[type="text"]');
                newIngredientInput.value = ""; // Reset the value to an empty string

                // Update the input names and IDs based on the new form count
                let totalForms = parseInt(totalFormsInput.value);
                clonedForm.innerHTML = clonedForm.innerHTML.replace(
                    /form-\d+/g,
                    `form-${totalForms}`
                );

                formsetContainer.appendChild(clonedForm);

                // Increment the TOTAL_FORMS value
                totalFormsInput.value = totalForms + 1;
            });
        });
    </script>
</body>

</html>